#!/bin/bash
if [ $# -eq 0 ]; then 
   echo " nothing has been inputted"
   exit 1
fi
input_file="$2"
if [ ! -f "$input_file" ]; then
   echo "file not found" >&2
   exit 1
fi
func=$1
while read -r teststems; do
    for element in $teststems; do
        desc_file="${element}.in"
        diff_file="${element}.out"
        args_file="${element}.args"
        new_temp=$(mktemp)
        $func < $desc_file > $new_temp
        DIFF=$(diff "$new_temp" "$diff_file")
        if [ -f "$desc_file" ] && [ -f "$diff_file" ]; then
            if [ "$DIFF" != "" ]; then
                echo "Test $element failed"
                echo "Expected output: "
                cat "$diff_file"
                echo "Actual output: "
                cat "$new_temp"
            else
                echo "Test $element passed"
            fi
        else
            echo "no difference file or no stem file "
        fi
    done
done < "$input_file"
