#!/bin/bash
if [ $# -eq 0 ]; then 
   echo " nothing has been inputted"
fi
input_file="$2"
if [ ! -f "$input_file" ]; then
   echo "file not found" >&2
fi
func=$1
while read -r teststems; do
    for element in $teststems; do
        if [ -e "${element}.in" ]; then
            desc_file="${element}.in"
        else
            echo "no in file"
        fi
        if [ -e "${element}.out" ]; then
            diff_file="${element}.out"
        else 
            echo "no out file"
        fi
        if [ -e "${element}.args" ]; then
            args_file="${element}.args"
        else
            echo "no args file"
        fi
        new_temp=$(mktemp)
        $func $(cat "$args_file") < $desc_file > $new_temp
        DIFF=$(diff "$new_temp" "$diff_file")
        if [ -f "$desc_file" ] && [ -f "$diff_file" ]; then
            if [ "$DIFF" != "" ]; then
                echo "Test $element failed"
                echo "Expected output: "
                cat "$diff_file"
                echo "Actual output: "
                cat "$new_temp"
            else
                echo "Test $element passed"
            fi
        fi
    done
done < "$input_file"
